### ISSUE TITLE
Fail gracefully when database hits max size

### ISSUE THREAD

**Issue by DrHyde** [DBM-Deep/DBM-Deep#2]
Originally reported by @Pascal666 at https://rt.cpan.org/Ticket/Display.html?id=130395 and https://github.com/robkinyon/dbm-deep/issues/24

Maximum database size is determined by pack_size when the database is created. Currently, when the database gets too big it gets corrupted and programs using the database yield various random errors. It would be nice if DBM::Deep would fail gracefully when the database hits its maximum size, yielding an error message like "Database full: recreate using larger pack_size".

Code to reproduce:

```perl
require DBM::Deep;

my $filename = 'test.db';

DBM::Deep->new(
    file      => $filename,
    pack_size => 'small',
);

tie my %db, 'DBM::Deep', $filename;

for (0..99999) {
    $db{$_} = $_;
}
```

Output from the above:

```
[root@perltest DBM]# ./pack_size.pl
DBM::Deep: Cannot read sector at 4598 in get_bucket_list() at ./pack_size.pl line 18
[root@perltest DBM]# ./pack_size.pl
DBM::Deep: '161': Don't know what to do with type '▒' at ./pack_size.pl line 18
[root@perltest DBM]# ./pack_size.pl
Can't call method "free" on an undefined value at /usr/local/share/perl5/5.32/DBM/Deep/Sector/File/Reference.pm line 152.
```

**Comment by DrHyde** [comment]
Same bug happens when using a normal object instead of tieing.

**Comment by DrHyde** [comment]
I have a fix in branch `fail-gracefully-when-exceeding-max-size`. Gonna torture it for a bit before making a test release.

**Comment by DrHyde** [comment]
There's a test version 2.0018_01 on its way to the CPAN now. If the CPAN-testers are happy with it then I'll release 2.0019 with the fix in some time next week.

**Comment by DrHyde** [comment]
Version 2.0019 is on its way to the CPAN with a fix.

**Comment by Pascal666** [comment]
Thank you for fixing this.  I can confirm that on v2.0019 both pack_size small and medium now issue a warning when the database is full, instead of corrupting it.

I opened this bug report right after losing a 4GB database.  I was able to restore from the previous night's backup, but still lost a lot of data and spent many hours finding the problem, restoring, and migrating the database to pack_size large.

Hopefully, this patch will prevent anyone else from going through the same thing.
